### ISSUE TITLE
AttributeError: 'Packet' object has no attribute 'cmd'

### ISSUE THREAD

**Issue by Alsares** [Ramir0/Myo4Linux#2]
Hi,
When I execute "test_myo.py" the script find the Myo, but can't print the action (rest, fist, wave, . ..)

Start Myo for Linux
Find Myo device...
Connected.
Firmware version: 1.3.1448.2
Device name: Myo
Finished.
Traceback (most recent call last):
  File "test_myo.py", line 29, in <module>
    main()
  File "test_myo.py", line 18, in main
    myo.run()
  File "../lib/myo.py", line 50, in run
    self.ble.receive_packet(timeout)
  File "../lib/ble.py", line 23, in receive_packet
    self.notify_event(packet)
  File "../lib/ble.py", line 49, in notify_event
    listener.handle_data(p)
  File "../lib/device_listener.py", line 5, in handle_data
    if data.cls != 4 and data.cmd != 5:
AttributeError: 'Packet' object has no attribute 'cmd'

I try in Ubuntu 14.04, same things with Raspbian on Raspberry Pi 2.

**Comment by love12734** [comment]
same error
Answer Plz

**Comment by AVGP** [comment]
I've got a fix for that. See #4 for details.

**Comment by zerbo88** [comment]
unfortunately for me the example test_myo not press any installation, why?
